// Generated by LiveScript 1.4.0
var HelloWorld;
HelloWorld = (function(){
  HelloWorld.displayName = 'HelloWorld';
  var prototype = HelloWorld.prototype, constructor = HelloWorld;
  HelloWorld.test = 'test';
  function HelloWorld(){}
  return HelloWorld;
}());
